import type { MessagePresentation } from "openclaw/plugin-sdk/interactive-runtime";
import { describe, expect, it } from "vitest";
import { markdownToBasecampHtml } from "../src/outbound/format.js";
import {
  BASECAMP_PRESENTATION_CAPABILITIES,
  renderBasecampPresentationMarkdown,
} from "../src/outbound/presentation.js";

// ---------------------------------------------------------------------------
// Capabilities contract (SPEC §3.1, probe results from §8 Q4)
// ---------------------------------------------------------------------------

describe("presentation.capabilities", () => {
  it("matches the Basecamp presentation contract", () => {
    expect(BASECAMP_PRESENTATION_CAPABILITIES).toEqual({
      supported: true,
      buttons: false,
      selects: false,
      context: true,
      divider: true,
      charts: false,
      tables: true,
      limits: {
        text: { maxLength: 10_000, encoding: "characters", markdownDialect: "markdown" },
      },
    });
  });
});

// ---------------------------------------------------------------------------
// renderBasecampPresentationMarkdown
// ---------------------------------------------------------------------------

describe("presentation.render", () => {
  it("renders title as an h1 heading through the HTML pipeline", () => {
    const md = renderBasecampPresentationMarkdown({ title: "Build Report", blocks: [] });
    expect(md).toBe("# Build Report");
    expect(markdownToBasecampHtml(md!)).toContain("<h1>Build Report</h1>");
  });

  it("renders text blocks as body paragraphs", () => {
    const md = renderBasecampPresentationMarkdown({
      blocks: [
        { type: "text", text: "First." },
        { type: "text", text: "Second." },
      ],
    });
    expect(md).toBe("First.\n\nSecond.");
  });

  it("renders context blocks as blockquotes", () => {
    const md = renderBasecampPresentationMarkdown({
      blocks: [{ type: "context", text: "generated by agent\nline two" }],
    });
    expect(md).toBe("> generated by agent\n> line two");
    expect(markdownToBasecampHtml(md!)).toContain("<blockquote>");
  });

  it("renders dividers as horizontal rules", () => {
    const md = renderBasecampPresentationMarkdown({
      blocks: [{ type: "text", text: "above" }, { type: "divider" }, { type: "text", text: "below" }],
    });
    expect(md).toBe("above\n\n---\n\nbelow");
    expect(markdownToBasecampHtml(md!)).toContain("<hr>");
  });

  it("renders tables as Markdown pipe tables that convert to <table>", () => {
    const md = renderBasecampPresentationMarkdown({
      blocks: [
        {
          type: "table",
          caption: "Uptime",
          headers: ["Service", "Status"],
          rows: [
            ["web", "up"],
            ["worker", "down"],
          ],
        },
      ],
    });
    expect(md).toContain("**Uptime**");
    expect(md).toContain("| Service | Status |");
    expect(md).toContain("| web | up |");
    const html = markdownToBasecampHtml(md!);
    expect(html).toContain("<table>");
    expect(html).toContain("<th>Service</th>");
    expect(html).toContain("<td>down</td>");
  });

  it("escapes pipe characters inside table cells", () => {
    const md = renderBasecampPresentationMarkdown({
      blocks: [{ type: "table", caption: "", headers: ["Cmd"], rows: [["a | b"]] }],
    });
    expect(md).toContain("a \\| b");
  });

  it("renders button blocks as fallback text with URLs, never callback IDs", () => {
    const md = renderBasecampPresentationMarkdown({
      blocks: [
        {
          type: "buttons",
          buttons: [
            { label: "Open Docs", action: { type: "url", url: "https://example.com/docs" } },
            { label: "Approve", action: { type: "callback", value: "secret-callback-id" } },
          ],
        },
      ],
    } as MessagePresentation);
    expect(md).toContain("Open Docs");
    expect(md).toContain("https://example.com/docs");
    expect(md).toContain("Approve");
    expect(md).not.toContain("secret-callback-id");
  });

  it("renders select blocks as option label lists", () => {
    const md = renderBasecampPresentationMarkdown({
      blocks: [
        {
          type: "select",
          placeholder: "Pick one",
          options: [
            { label: "Option A", value: "a" },
            { label: "Option B", value: "b" },
          ],
        },
      ],
    } as MessagePresentation);
    expect(md).toContain("Option A");
    expect(md).toContain("Option B");
  });

  it("renders chart blocks as deterministic fallback text", () => {
    const md = renderBasecampPresentationMarkdown({
      blocks: [
        {
          type: "chart",
          chartType: "pie",
          title: "Share",
          segments: [
            { label: "A", value: 60 },
            { label: "B", value: 40 },
          ],
        },
      ],
    } as MessagePresentation);
    expect(md).toContain("Share");
    expect(md).toContain("A");
    expect(md).toContain("60");
  });

  it("returns null for a presentation with no visible content", () => {
    expect(renderBasecampPresentationMarkdown({ blocks: [] })).toBeNull();
    expect(renderBasecampPresentationMarkdown({ blocks: [{ type: "text", text: "   " }] })).toBeNull();
  });

  it("composes a full presentation in block order", () => {
    const md = renderBasecampPresentationMarkdown({
      title: "Deploy",
      blocks: [{ type: "text", text: "All green." }, { type: "divider" }, { type: "context", text: "took 42s" }],
    });
    expect(md).toBe("# Deploy\n\nAll green.\n\n---\n\n> took 42s");
  });
});
